"""Add feature_task_timer to User

Revision ID: 9c40f1a66011
Revises: e22c58f284ee
Create Date: 2025-08-25 09:14:13.499617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c40f1a66011'
down_revision = 'e22c58f284ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feature_task_stats', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('feature_task_stats')

    # ### end Alembic commands ###
