"""Update User model (add dashboard_features)

Revision ID: e22c58f284ee
Revises: 74899d74af3c
Create Date: 2025-08-25 08:24:50.646417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22c58f284ee'
down_revision = '74899d74af3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_task')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
              sa.Column('dashboard_features', sa.JSON(), nullable=False, server_default='{}')
       )
        batch_op.add_column(sa.Column('feature_task_timer', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feature_focus_mode', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feature_deadline_tracker', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feature_priority_sort', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feature_task_export', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feature_progress_graphs', sa.Boolean(), nullable=True))
        batch_op.alter_column('avatar_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('registered_on',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('registered_on',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=300),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('feature_progress_graphs')
        batch_op.drop_column('feature_task_export')
        batch_op.drop_column('feature_priority_sort')
        batch_op.drop_column('feature_deadline_tracker')
        batch_op.drop_column('feature_focus_mode')
        batch_op.drop_column('feature_task_timer')
        batch_op.drop_column('dashboard_features')

    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    op.create_table('_alembic_tmp_task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('reminder_set', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
